/* Generated By:JavaCC: Do not edit this line. PediaIconsConstants.java */
package ressource.parser;

public interface PediaIconsConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 4;
  int EOL = 10;
  int TEXT = 11;
  int KEY = 12;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\";\"",
    "\"##\"",
    "\"# \"",
    "<SINGLE_LINE_COMMENT>",
    "<token of kind 5>",
    "\"\\t\"",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "<EOL>",
    "<TEXT>",
    "<KEY>",
  };

}
