/* Generated By:JavaCC: Do not edit this line. ScriptConstants.java */
package ressource.parser;

public interface ScriptConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 5;
  int EOL = 11;
  int DIESE = 12;
  int WAVE = 13;
  int CAPTION = 14;
  int MAP_CENTER = 15;
  int XS = 16;
  int NOMBRE = 17;
  int KEY = 18;
  int TEXT = 19;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\";\"",
    "\"##\"",
    "\"# \"",
    "\"#comment\"",
    "<SINGLE_LINE_COMMENT>",
    "<token of kind 6>",
    "\"\\t\"",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "<EOL>",
    "\"#\"",
    "\"wave\"",
    "\"caption\"",
    "\"map_center\"",
    "\"xs\"",
    "<NOMBRE>",
    "<KEY>",
    "<TEXT>",
  };

}
